### ISSUE TITLE
Unable to sort nodes by system properties `ECClassId` and `ECInstanceId`

### ISSUE THREAD

**Issue by grigasp** [iTwin/imodel-native#602]
The [PropertySortingRule](https://github.com/iTwin/itwinjs-core/blob/9c6ca930ee6abfe860c16465a1bd0933448f00fe/presentation/common/src/presentation-common/rules/customization/SortingRule.ts#L47-L60) accepts name of the property to use for sorting, but that doesn't work with system properties `ECClassId` and `ECInstanceId`. They should be supported as well.

**Comment by muthubentley** [comment]
@grigasp  can you please confirm which package and version this fix has been released to?

**Comment by grigasp** [comment]
> @grigasp can you please confirm which package and version this fix has been released to?

Hey. This is included in the newly released itwinjs-core `4.4.0` release.
